default:
  target: target
  outputs:
    target:
      type: bigquery
      method: oauth
      project: "{{ env_var('PROJECT_ID') }}"
      dataset: "{{ env_var('DEFAULT_DATASET') }}"
      threads: 4
      timeout_seconds: 300
      location: "{{ env_var('LOCATION') }}"
      priority: interactive