name: 'dbt_ga'
version: '1.0.0'
config-version: 2
profile: 'default'
source-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  dbt_ga4:
      ga:
        # materialize all models in models/ga as tables
        +materialized: table
