
version: 2
sources:
  - name: analytics_272722196
    tables:
      - name: events_*
models:
    - name: ga_events
      description: "Google Analytics のデータを解析しやすいように加工した view"
    - name: user_list
      description: "ユーザーID一覧"
      columns:
          - name: user_pseudo_id
            description: "ユーザ毎に一位のIDを羅列したマスタview"
            tests:
                - unique
    - name: daily_unique_user
      description: "Daily ユニークユーザーのサマリーテーブル"
      columns:
          - name: event_date
            description: "日付"
            tests:
                - unique

